[package]
name = "mathmap-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.101"
image = { version = "0.25.8", default-features = false, features = ["png", "gif"] }
mathmap = { path = ".." }
