name: web

# on:
#   push:
#     branches:
#       - main
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Set up rust build cache
        uses: Swatinem/rust-cache@v2

      - name: Install wasm-bindgen
        run: cargo install --version 0.2.101 wasm-bindgen-cli

      - name: Build WASM
        run: make build
        working-directory: ./wasm

      # https://github.com/actions/upload-pages-artifact
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: wasm/web

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      pages: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
